### PR TITLE
upgraded to NZBGet 14.2

### PR DESCRIPTION
**Pull request by disrupted**

### CODE REVIEW

**Comment by CurlyMoo** [comment]
You have direct access so use it :+1:

**Comment by freeman212** [comment]
yeah noticed that too right after I commited the changes to my fork :D do you think it makes sense that I also push the latest testing release (nzbget-15.0-r1207) to a separate branch and to the devel apt repo?

**Comment by CurlyMoo** [comment]
You're free do to with nzbget whatever you want as long as it isn't illegal.

**Comment by freeman212** [comment]
okay, sure. I'm always using the official source code.

**Comment by freeman212** [comment]
think I'm gonna update the other packages too very soon (especially sickbeard -> sickrage) if that's okay.

**Comment by CurlyMoo** [comment]
Yes

**Pull request merged**
