### PR TITLE
update to latest stable NZBGet 14.1

### PR DESCRIPTION
**Pull request by freeman212**
this is my first package for the XBian, so hopefully I didn't break anything. ;-) packaged the deb and upgraded my installed NZBGet without any problems so it should be safe.
GnuTLS shouldn't be required anymore since we use the faster OpenSSL.
Kind Regards :)

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Would you like to maintain this package more regularly?

**Comment by freeman212** [comment]
yes, I would love to, even created a new branch for test releases already. if everything runs smoothly I could even look into updating other packages like SickBeard or SickRage :) I want to contribute more actively to the awesome developerment behind XBian/Kodi in general

**Comment by CurlyMoo** [comment]
Nice. If you can get confirmation (on the forum) that your debs work, i will give you access to our apt repository so you can upload them directly.

**Comment by freeman212** [comment]
okay thank you. I'm glad to be part of such a truly wonderful community :-)

**Comment by freeman212** [comment]
just fixed a little typo in one of the conf files and installed it without any problems on a fresh XBian installation. now I'll post the *.deb image on the forum. hopefully it doesn't take long until I get the confirmation from someone ;-)

**Comment by CurlyMoo** [comment]
We've discussed (@mk01 and I) the future of these packages. What we would prefer is some sort of `meta` package. E.g. the sickbeard package should not include the source of sickbeard, but instead just clone the source from git while installing. So, the only files included in the package should be the config. Updates can be managed from inside sickbeard. That would make these packages far easier maintainable.

**Comment by freeman212** [comment]
I agree, sounds like a good idea for sickbeard & co, but nzbget isn't updatable from within the application, so I will maintain and update it manually. maybe we should discuss things like that together somewhere ;-) i was thinking about migrating to a different sickbeard fork, because the current one (sickbeard-tpb) is fairly outdated.

**Comment by CurlyMoo** [comment]
We always discuss stuff in irc.

**Comment by CurlyMoo** [comment]
What about create a auto-configure-build package just like xbian-package-kernel (as the most advanced example).

**Comment by freeman212** [comment]
not sure if I can handle this.. but having one package and doing the rest via "git pull" should also do the trick, right?

**Comment by CurlyMoo** [comment]
What about describing the full build / patch steps somewhere?

**Comment by freeman212** [comment]
you mean the build steps for the nzbget paclage right? can't post them until the end of the week when I'm back at home and have a computer. then I can also push the package to the apt repo. (btw has it already been confirmed to be working from someone else than me?)

**Comment by CurlyMoo** [comment]
No, How annoying right :)

**Comment by freeman212** [comment]
still no reply :( so when can I publish the updated package to the apt repo?

**Comment by CurlyMoo** [comment]
Please join me in #xbian irc at 21:00 UTC+1

**Comment by freeman212** [comment]
been ages since I set up IRC for the last time, but still seems like a good idea ;-)

**Pull request merged**
